name: Test
on:
  pull_request:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  test_macos:
    name: Test (MacOS)
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup | Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: macos-test-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Lint
        run: |
          cargo clippy -- --deny warnings
      - name: Build test
        run: cargo build
  test_linux:
    name: Test (Linux)
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup | Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: linux-test-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Lint
        run: |
          cargo clippy -- --deny warnings
      - name: Build test
        run: cargo build
